From SimpleC.EE.LLM_bench.Algorithms.container_with_most_water_linear Require Import container_with_most_water_linear_goal container_with_most_water_linear_proof_auto container_with_most_water_linear_proof_manual.

Module VC_Correctness : VC_Correct.
  Include int_array_strategy_proof.
  Include uint_array_strategy_proof.
  Include undef_uint_array_strategy_proof.
  Include array_shape_strategy_proof.
  Include container_with_most_water_linear_proof_auto.
  Include container_with_most_water_linear_proof_manual.
End VC_Correctness.
