Require Import Coq.ZArith.ZArith.
Require Import Coq.Bool.Bool.
Require Import Coq.Strings.String.
Require Import Coq.Strings.Ascii.
Require Import Coq.Lists.List.
Require Import Coq.Classes.RelationClasses.
Require Import Coq.Classes.Morphisms.
Require Import Coq.micromega.Psatz.
Require Import Coq.Sorting.Permutation.
From AUXLib Require Import int_auto Axioms Feq Idents ListLib VMap.
Require Import SetsClass.SetsClass. Import SetsNotation.
From SimpleC.SL Require Import Mem SeparationLogic.
From SimpleC.EE.LLM_bench.Algorithms.extended_chinese_remainder_theorem Require Import extended_chinese_remainder_theorem_goal.
Require Import Logic.LogicGenerator.demo932.Interface.
Local Open Scope Z_scope.
Local Open Scope sets.
Local Open Scope string_scope.
Local Open Scope list.
Import naive_C_Rules.
Require Import SimpleC.EE.LLM_bench.Algorithms.modular_mul.modular_mul_lib.
Require Import SimpleC.EE.LLM_bench.Algorithms.extended_chinese_remainder_theorem.extended_chinese_remainder_theorem_lib.
Local Open Scope sac.

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_1 : extended_chinese_remainder_theorem_safety_wit_1.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_2 : extended_chinese_remainder_theorem_safety_wit_2.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_3 : extended_chinese_remainder_theorem_safety_wit_3.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_4 : extended_chinese_remainder_theorem_safety_wit_4.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_5 : extended_chinese_remainder_theorem_safety_wit_5.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_6 : extended_chinese_remainder_theorem_safety_wit_6.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_8 : extended_chinese_remainder_theorem_safety_wit_8.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_10 : extended_chinese_remainder_theorem_safety_wit_10.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_11 : extended_chinese_remainder_theorem_safety_wit_11.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_22 : extended_chinese_remainder_theorem_safety_wit_22.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_23 : extended_chinese_remainder_theorem_safety_wit_23.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_24 : extended_chinese_remainder_theorem_safety_wit_24.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_25 : extended_chinese_remainder_theorem_safety_wit_25.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_26 : extended_chinese_remainder_theorem_safety_wit_26.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_27 : extended_chinese_remainder_theorem_safety_wit_27.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_28 : extended_chinese_remainder_theorem_safety_wit_28.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_safety_wit_29 : extended_chinese_remainder_theorem_safety_wit_29.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_1 : extended_chinese_remainder_theorem_partial_solve_wit_1.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_2 : extended_chinese_remainder_theorem_partial_solve_wit_2.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_3 : extended_chinese_remainder_theorem_partial_solve_wit_3.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_4 : extended_chinese_remainder_theorem_partial_solve_wit_4.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_5 : extended_chinese_remainder_theorem_partial_solve_wit_5.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_6 : extended_chinese_remainder_theorem_partial_solve_wit_6.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_7 : extended_chinese_remainder_theorem_partial_solve_wit_7.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_8 : extended_chinese_remainder_theorem_partial_solve_wit_8.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_9 : extended_chinese_remainder_theorem_partial_solve_wit_9.
Proof. Admitted. 

Lemma proof_of_extended_chinese_remainder_theorem_partial_solve_wit_10 : extended_chinese_remainder_theorem_partial_solve_wit_10.
Proof. Admitted. 

