From SimpleC.EE.LLM_bench.Algorithms.linear_modular_inverse Require Import linear_modular_inverse_goal linear_modular_inverse_proof_auto linear_modular_inverse_proof_manual.

Module VC_Correctness : VC_Correct.
  Include linear_modular_inverse_proof_auto.
  Include linear_modular_inverse_proof_manual.
End VC_Correctness.
