/*@ Import Coq Require Import SimpleC.EE.Applications_human.minisat.solver_qcp_lib */

/* Ghost types shared by the MiniSat translation unit. */
/*@ Extern Coq
      (literal :: *)
      (clause :: *)
      (clause_obj :: *)
      (cnf :: *)
      (msolver :: *)
      (solver_propagation_context :: *)
      (analyze_resolution_phase :: *)
      (cdcl_view :: *)
      (mtrail :: *)
      (mheap :: *)
      (dbmap :: *)
 */

/*@ Extern Coq
      (map : {A} {B} -> (A -> B) -> list A -> list B)
      (In : {A} -> A -> list A -> Prop)
      (incl : {A} -> list A -> list A -> Prop)
      (Forall : {A} -> (A -> Prop) -> list A -> Prop)
      (tl : {A} -> list A -> list A)
      (NoDup : {A} -> list A -> Prop)
      (Permutation : {A} -> list A -> list A -> Prop)
      (repeat_Z : {A} -> A -> Z -> list A)
      (Z::max : Z -> Z -> Z)
      (db_words : dbmap -> list Z)
      (db_nil : dbmap)
      (z_nil : list Z)
      (msat_true : bool)
      (msat_false : bool)
 */

/* Double-array carriers used by the variable-activity annotations. */
/*@ Extern Coq
      (veci_rep : Z -> list Z -> Z -> Assertion)
      (veci_rep_at : Z -> Z -> list Z -> Z -> Assertion)
      (vecp_rep : Z -> list Z -> Z -> Assertion)
      (vecp_rep_at : Z -> Z -> list Z -> Z -> Assertion)
      (vecp_size_addr : Z -> Z)
      (vecp_cap_addr : Z -> Z)
      (vecp_ptr_addr : Z -> Z)
      (solver_clause_count_cell : Z -> Z -> Assertion)
      (DoubleArray::seg : Z -> Z -> Z -> list fp64 -> Assertion)
      (DoubleArray::missing_i : Z -> Z -> Z -> Z -> list fp64 -> Assertion)
      (DoubleArray::undef_seg : Z -> Z -> Z -> Assertion)
      (double_array_missing2 : Z -> Z -> Z -> Z -> list fp64 -> Assertion)
      (double_Znth : Z -> list fp64 -> fp64)
      (Z_to_fp64 : Z -> fp64)
      (msat_fp32_same : fp32 -> fp32 -> Prop)
      (msat_fp32_nonnegative : fp32 -> Prop)
      (msat_fp32_positive_finite : fp32 -> Prop)
      (msat_fp32_count_limit : Z -> fp32 -> Prop)
      (lbool_cell : Z -> Prop)
      (co_lits : clause_obj -> list Z)
      (co_learnt : clause_obj -> bool)
      (PropagationStable : list literal -> solver_propagation_context)
      (PropagationAssuming : list literal -> solver_propagation_context)
      (valid_int_position : Z -> Prop)
      (cnf_wf : Z -> cnf -> Prop)
 */

/* Function and public-boundary contracts. */
/*@ Extern Coq
      (model_saved : Z -> cnf -> list literal -> msolver -> Prop)
      (solver_normal_root : Z -> cnf -> msolver -> Prop)
      (solver_sat_cancel_ready : Z -> cnf -> list literal -> msolver -> Prop)
      (solver_operational_root : Z -> cnf -> msolver -> Prop)
      (solver_holds_formula : Z -> cnf -> msolver -> Prop)
      (msolver_resume : msolver -> msolver)
      (solver_sat_arm : Z -> Z -> cnf -> list literal -> msolver -> Assertion)
      (solver_unsat_arm : Z -> Z -> cnf -> list literal -> msolver -> Assertion)
      (solver_capacity_arm : Z -> Z -> cnf -> msolver -> Assertion)
      (solver_propagate_pre : Z -> Z -> Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_propagate_post : Z -> Z -> Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> Z -> Z -> Assertion)
      (propagation_caller_frame : msolver -> msolver -> Prop)
      (solver_simplify_pre_at : Z -> Z -> cnf -> list literal -> msolver -> Z -> Z -> Assertion)
      (solver_simplify_post_at : Z -> Z -> cnf -> list literal -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_search_pre : Z -> Z -> cnf -> list literal -> list literal -> msolver -> Z -> Assertion)
      (minisat_base_watch_completed : msolver -> Prop)
      (minisat_watch_conflict_ready : Z -> msolver -> Prop)
      (minisat_resident_false_clause : msolver -> Prop)
      (record_watch1_positive : msolver -> list Z -> Prop)
      (solver_search_reuse : msolver -> msolver -> Prop)
      (solver_search_conflict_reuse : Z -> cnf -> list literal -> list literal -> msolver -> Prop)
      (solver_query_watch_ready : msolver -> Prop)
      (solver_base_recovery : Z -> cnf -> msolver -> Prop)
      (solver_query_entry : Z -> cnf -> msolver -> Prop)
      (solver_base_state : Z -> cnf -> msolver -> Prop)
      (solver_rep : Z -> msolver -> Assertion)
      (solver_sat_arm_at : Z -> Z -> cnf -> list literal -> msolver -> msolver -> Z -> Assertion)
      (solver_unsat_arm_at : Z -> Z -> cnf -> list literal -> msolver -> msolver -> Z -> Assertion)
      (solver_capacity_arm_at : Z -> Z -> cnf -> msolver -> msolver -> Z -> Assertion)
      (solver_simplify_post_sat_at : Z -> Z -> cnf -> list literal -> msolver -> Z -> Z -> Assertion)
      (solver_simplify_post_unsat_at : Z -> Z -> cnf -> list literal -> msolver -> Z -> Z -> Assertion)
      (solver_simplify_post_retry_at : Z -> Z -> cnf -> list literal -> msolver -> Z -> Z -> Assertion)
      (solver_search_result : Z -> Z -> cnf -> list literal -> list literal -> Z -> Z -> msolver -> Assertion)
      (solver_search_loop : Z -> Z -> Z -> Z -> cnf -> list literal -> list literal -> Z -> msolver -> Assertion)
      (solver_search_init_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_search_root_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_search_root_payload : Z -> msolver -> Z -> Assertion)
      (solver_search_conflict_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_search_decay_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_search_reducedb_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_search_progress_frame_at : Z -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_search_order_frame_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (solver_search_backjump_ready : Z -> cnf -> list literal -> list literal -> msolver -> msolver -> list Z -> Prop)
      (solver_search_selection_state : Z -> cnf -> list literal -> list literal -> Z -> msolver -> Prop)
      (solver_search_model_ready : Z -> cnf -> list literal -> list literal -> msolver -> Prop)
      (solver_search_select_transition : Z -> cnf -> list literal -> list literal -> msolver -> Z -> list Z -> list Z -> fp64 -> list Z -> msolver -> Prop)
      (solver_search_decision_transition : Z -> cnf -> list literal -> list literal -> msolver -> Z -> Z -> msolver -> Prop)
      (model_copy_progress : Z -> msolver -> list Z -> Z -> Prop)
      (model_copy_finish : Z -> cnf -> list literal -> list literal -> msolver -> list Z -> Z -> msolver -> Prop)
      (solver_simplify_reuse : msolver -> msolver -> Prop)
      (solver_simplify_outer_loop : Z -> Z -> cnf -> list literal -> Z -> Z -> Z -> msolver -> Z -> Assertion)
      (solver_selected_db : Z -> msolver -> dbmap)
      (solver_selected_vec : Z -> Z -> Z)
      (solver_selected_cap : Z -> msolver -> Z)
      (solver_selected_is_learnt : Z -> bool)
      (solver_selected_prob_db : Z -> msolver -> dbmap)
      (solver_selected_learnt_db : Z -> msolver -> dbmap)
      (solver_simplify_clause_frame_at : Z -> Z -> msolver -> Z -> Z -> Assertion)
      (solver_simplify_db_rest_at : Z -> Z -> msolver -> Z -> Z -> Z -> Z -> Assertion)
      (solver_simplify_finish_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_simplify_db_compaction_inv : Z -> msolver -> list Z -> Z -> Z -> Prop)
      (solver_simplify_keep_words : list Z -> Z -> Z -> list Z)
      (solver_simplify_compaction_step : Z -> cnf -> list literal -> Z -> msolver -> list Z -> Z -> Z -> msolver -> list Z -> Z -> Prop)
      (solver_simplify_finish_transition : Z -> cnf -> list literal -> msolver -> Z -> msolver -> Prop)
      (solver_rep_reasons_levels_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_rep_levels_at : Z -> msolver -> Z -> Assertion)
      (solver_rep_levels_wl_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_rep_analyze_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (solver_rep_assigns_levels_at : Z -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_rep_reasons_levels_wl_at : Z -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_assigns_focus_frame_at : Z -> msolver -> Z -> Assertion)
      (solver_solve_entry_rest_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_model_copy_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_simplify_lim_frame_at : Z -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_simplify_control_frame_at : Z -> msolver -> Z -> Z -> Z -> Z -> Assertion)
      (solver_assume_frame_wl : Z -> msolver -> Z -> Assertion)
  (solver_assume_frame : Z -> msolver -> Assertion)
      (solver_root_install_frame_at : Z -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_resume_frame_at : Z -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_query_reuse : msolver -> msolver -> Prop)
      (solver_terminal_reuse : Z -> cnf -> list literal -> msolver -> msolver -> Z -> Prop)
      (solver_restart_loop : Z -> Z -> Z -> Z -> cnf -> list literal -> Z -> Z -> msolver -> Assertion)
      (solver_lit_removable_pre : Z -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> Assertion)
      (solver_lit_removable_post : Z -> Z -> Z -> Z -> Z -> Z -> Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_analyze_pre : Z -> Z -> Z -> Z -> Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> clause -> Z -> Z -> Assertion)
      (solver_analyze_post : Z -> Z -> Z -> Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> Assertion)
      (msolver_with_cla_inc_stats : msolver -> fp32 -> list Z -> msolver)
      (record_clause_cert : Z -> cnf -> msolver -> list Z -> Prop)
      (analyze_clause_cert : Z -> cnf -> msolver -> list Z -> Prop)
      (analyze_backjump_cert : Z -> msolver -> list Z -> Z -> Prop)
 */

/* Clause allocation, recording, cancellation, and assumption transitions. */
/*@ Extern Coq
      (clause_allocator_fresh : msolver -> Z -> Prop)
      (clause_new_capacity_failure : Z -> cnf -> list literal -> list literal -> msolver -> msolver -> list Z -> Prop)
      (clause_new_success_transition : Z -> cnf -> list literal -> list literal -> msolver -> list Z -> Z -> msolver -> Prop)
      (record_allocated : Z -> cnf -> list literal -> list literal -> msolver -> list Z -> Z -> msolver -> Prop)
      (record_enqueue_success : Z -> cnf -> list literal -> list literal -> msolver -> msolver -> list Z -> Z -> msolver -> Prop)
      (record_finish_success : Z -> cnf -> list literal -> list literal -> msolver -> msolver -> list Z -> Z -> fp32 -> msolver -> Prop)
      (record_output : Z -> cnf -> list literal -> list literal -> msolver -> msolver -> list Z -> Z -> msolver -> Prop)
      (solver_record_pre_at : Z -> Z -> Z -> Z -> cnf -> list literal -> list literal -> msolver -> list Z -> Z -> Z -> Assertion)
      (solver_record_post_at : Z -> Z -> Z -> Z -> cnf -> list literal -> list literal -> msolver -> list Z -> Z -> Z -> Z -> Assertion)
      (solver_reducedb_pre_at : Z -> Z -> Z -> cnf -> list literal -> list literal -> msolver -> Z -> Assertion)
      (solver_reducedb_post_at : Z -> Z -> Z -> cnf -> list literal -> list literal -> msolver -> Z -> Assertion)
      (solver_cancel_owned : Z -> msolver -> Z -> Assertion)
  (solver_cancel_pre : Z -> Z -> msolver -> Z -> Assertion)
      (solver_cancel_post : Z -> Z -> msolver -> Z -> Assertion)
      (solver_prepare_capacity_pre : Z -> Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Assertion)
      (solver_cancel_capacity_post : Z -> Z -> cnf -> msolver -> Z -> Assertion)
      (solver_cancel_capacity_focus : Z -> cnf -> msolver -> Z -> Z -> Z -> Z -> Z -> list Z -> list Z -> Z -> Z -> Prop)
      (msolver_publish_capacity : msolver -> Z -> msolver)
      (solver_capacity_publication_transition : Z -> cnf -> msolver -> Z -> Prop)
      (solver_prepare_capacity_post : Z -> Z -> cnf -> msolver -> Z -> Assertion)
      (solver_public_capacity_frame : Z -> msolver -> Z -> Assertion)
      (assumption_prefix : list Z -> Z -> list literal)
      (assumption_true_advance : Z -> cnf -> list literal -> list Z -> Z -> msolver -> Prop)
      (assumption_fresh_ready : Z -> list Z -> Z -> msolver -> Prop)
      (assumption_fresh_transition : Z -> cnf -> list literal -> list Z -> Z -> Z -> msolver -> msolver -> Prop)
      (assumption_propagation_success : Z -> cnf -> list literal -> list Z -> Z -> msolver -> Prop)
      (assumption_root_install : Z -> cnf -> list literal -> msolver -> msolver -> list literal -> Prop)
      (AnalyzeInitial : analyze_resolution_phase)
      (AnalyzeSelected : analyze_resolution_phase)
 */

/* Solver capacity ownership; inline-vector declarations live in vec_qcp.h. */
/*@ Extern Coq
      (solver_watch_capacity_exhausted : msolver -> Prop)
      (solver_propagation_capacity_raw : Z -> Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_propagation_capacity_rest_at : Z -> msolver -> Z -> Z -> Z -> list (list Z) -> list (list Z) -> list Z -> list Z -> Z -> Z -> Assertion)
      (propagation_capacity_physical_alias : Z -> Z -> Z -> Z -> Z -> list (list Z) -> list (list Z) -> list Z -> list Z -> list Z -> Z -> Prop)
      (propagation_real_migrated_physical_alias : Z -> Z -> Z -> Z -> Z -> Z -> list (list Z) -> list (list Z) -> list Z -> Prop)
      (solver_internal_capacity_ready : Z -> cnf -> list literal -> list literal -> msolver -> Prop)
 */

/* Solver and trail projections. */
/*@ Extern Coq
      (ms_size : msolver -> Z)
      (ms_cap : msolver -> Z)
      (ms_qtail : msolver -> Z)
      (ms_core : msolver -> mtrail)
      (ms_model : msolver -> list Z)
      (ms_reason_words : msolver -> list Z)
      (ms_root_level : msolver -> Z)
      (ms_prob : msolver -> dbmap)
      (ms_prob_cap : msolver -> Z)
      (ms_learnt : msolver -> dbmap)
      (ms_learnt_cap : msolver -> Z)
      (ms_binary : msolver -> Z)
      (ms_binary_lits : msolver -> list Z)
      (ms_wm : msolver -> list (list Z))
      (ms_wcaps : msolver -> list Z)
      (ms_lim_cap : msolver -> Z)
      (ms_simpdb_assigns : msolver -> Z)
      (ms_simpdb_props : msolver -> Z)
      (ms_stats : msolver -> list Z)
      (stats_starts : list Z -> Z)
      (stats_decisions : list Z -> Z)
      (stats_propagations : list Z -> Z)
      (stats_inspects : list Z -> Z)
      (stats_conflicts : list Z -> Z)
      (stats_clauses : list Z -> Z)
      (stats_clauses_literals : list Z -> Z)
      (stats_learnts : list Z -> Z)
      (stats_learnts_literals : list Z -> Z)
      (stats_max_literals : list Z -> Z)
      (stats_tot_literals : list Z -> Z)
      (stats_set_conflicts : Z -> list Z -> list Z)
      (ms_cla_inc : msolver -> fp32)
      (ms_activity : msolver -> list fp64)
      (ms_orderpos : msolver -> list Z)
      (ms_order : msolver -> list Z)
      (ms_order_cap : msolver -> Z)
      (ms_tags : msolver -> list Z)
      (ms_tagged : msolver -> list Z)
      (ms_tagged_cap : msolver -> Z)
      (ms_stack : msolver -> list Z)
      (ms_stack_cap : msolver -> Z)
      (ms_var_inc : msolver -> fp64)
      (ms_var_decay : msolver -> fp64)
      (ms_cla_decay : msolver -> fp32)
      (ms_random_seed : msolver -> fp64)
      (ms_progress : msolver -> fp64)
      (ms_model_cap : msolver -> Z)
      (ms_capacity_pending_qhead : msolver -> Z)
      (ms_capacity_root_propagation_pending : msolver -> Z)
      (mt_assigns : mtrail -> list Z)
      (mt_levels : mtrail -> list Z)
      (mt_trail : mtrail -> list Z)
      (mt_lim : mtrail -> list Z)
      (mt_qhead : mtrail -> Z)
      (msolver_view : Z -> msolver -> cdcl_view)
      (msolver_heap : msolver -> mheap)
      (heap_wf : Z -> mheap -> Prop)
      (heap_covers : Z -> mheap -> list Z -> list Z -> Z -> Prop)
      (mtrail_wf : Z -> mtrail -> Prop)
      (current_level : cdcl_view -> Z)
      (level_of : cdcl_view -> Z -> option Z)
 */

/* Propagation and watcher ownership. */
/*@ Extern Coq
      (solver_shape : msolver -> Prop)
      (solver_nonlevel_rep : Z -> msolver -> Assertion)
      (msolver_inv : Z -> cnf -> list literal -> list literal -> msolver -> Prop)
      (msolver_inv_weak : Z -> cnf -> list literal -> list literal -> msolver -> Prop)
      (msolver_inv_assuming_strong : Z -> cnf -> list literal -> list literal -> msolver -> Prop)
      (solver_at_root : msolver -> Prop)
      (solver_propagation_inv : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Prop)
      (propagation_conflict_cert : Z -> cnf -> msolver -> clause -> Prop)
      (conflict_ptr_denotes : msolver -> Z -> clause -> Prop)
      (propagation_cancel_ready : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Prop)
      (analysis_cancel_ready : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Prop)
      (analysis_core_equiv : msolver -> msolver -> Prop)
      (analyze_inv : cnf -> cdcl_view -> list Z -> list Z -> clause -> Prop)
      (analyze_tags : list Z -> list Z -> clause -> list Z)
      (analysis_tags_exact : Z -> list Z -> list Z -> Prop)
      (reason_target_wf : Z -> msolver -> Z -> Z -> clause -> Prop)
      (analysis_clause_remainder : msolver -> Z -> bool -> list Z -> Assertion)
      (assigned_below_current : cdcl_view -> Z -> Prop)
      (minimize_tag_scope : Z -> msolver -> list Z -> list Z -> Prop)
      (removable_reason_focus : Z -> msolver -> Z -> Z -> clause -> Prop)
      (removable_reason_array_hole : Z -> Z -> Z -> list Z -> Assertion)
      (removable_dfs_loop_inv : Z -> msolver -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Prop)
      (removable_reason_scan_inv : Z -> msolver -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> clause -> Z -> Z -> Z -> Prop)
      (removable_rollback_inv : Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Prop)
      (analyze_resolution_loop_inv : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> analyze_resolution_phase -> Z -> clause -> list Z -> Z -> Z -> Z -> Prop)
      (analyze_clause_scan_inv : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> msolver -> Z -> analyze_resolution_phase -> clause -> Z -> Z -> list Z -> list Z -> clause -> Z -> list Z -> list Z -> clause -> list Z -> Z -> Prop)
      (analyze_tagged_step : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> msolver -> Z -> Z -> Z -> clause -> list Z -> list Z -> clause -> Z -> list Z -> list Z -> clause -> list Z -> Z -> Prop)
      (analyze_backward_scan_inv : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> list Z -> Z -> Z -> list Z -> list Z -> clause -> Prop)
      (analyze_resolution_exit : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> list Z -> Prop)
      (analyze_minimize_loop_inv : Z -> msolver -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Z -> Prop)
      (analyze_clear_loop_inv : Z -> Z -> list Z -> list Z -> list Z -> Prop)
      (analyze_max_loop_inv : Z -> msolver -> list Z -> Z -> Z -> Z -> Prop)
      (solver_propagation_loop_inv : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> msolver -> Z -> Prop)
      (propagation_watch_scan_physical : list Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Z -> Prop)
      (propagation_scan_frontier : msolver -> msolver -> Z -> Prop)
      (propagation_replacement_scan_inv : Z -> msolver -> Z -> list Z -> Z -> Prop)
      (solver_propagation_scan_semantics : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> list Z -> list Z -> Prop)
      (propagation_binary_conflict_scan_ready : Z -> msolver -> Z -> Z -> list Z -> Z -> Z -> Z -> Prop)
      (wlists_rep : Z -> Z -> list (list Z) -> list Z -> Assertion)
      (wlists_rep_from : Z -> Z -> list (list Z) -> list Z -> Assertion)
      (wlists_undef : Z -> Z -> Z -> Assertion)
      (solver_rep_growable : Z -> msolver -> Assertion)
      (setnvars_frame_at : Z -> msolver -> Assertion)
      (setnvars_arrays_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (setnvars_post_at : Z -> Z -> msolver -> cnf -> list literal -> list literal -> Z -> Z -> Assertion)
      (solver_support_inv : Z -> cnf -> list literal -> list literal -> Z -> msolver -> Prop)
      (setnvars_core_equiv : msolver -> msolver -> Prop)
      (setnvars_bound : Z -> Z -> Z -> Prop)
      (wlists_focus_at : Z -> Z -> list (list Z) -> list Z -> Z -> Assertion)
      (wlists_split_target_words : Z -> Z -> list (list Z) -> list (list Z) -> list Z)
      (wlists_split_target_cap : Z -> Z -> list Z -> list Z -> Z)
      (wlists_split_except_two : Z -> Z -> Z -> list (list Z) -> list (list Z) -> list Z -> list Z -> Assertion)
      (solver_wlists_handle : Z -> Z -> Assertion)
      (wlists_source_hole_handle : Z -> Z -> Z -> list (list Z) -> list (list Z) -> list Z -> list Z -> Assertion)
      (wlists_focused_handle : Z -> Z -> Z -> Z -> list (list Z) -> list Z -> list (list Z) -> list Z -> Z -> list Z -> Assertion)
      (wlists_destination_handle : Z -> Z -> Z -> Z -> Z -> list (list Z) -> list (list Z) -> list Z -> list Z -> Assertion)
      (propagation_destination_index : Z -> Z -> Z -> Prop)
      (vecp_slot : Z -> Z -> Z)
      (solver_binary_rep : msolver -> Assertion)
      (solver_propagate_frame : Z -> msolver -> Assertion)
      (solver_propagate_open_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (solver_propagation_nonwatch_rest_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_analyze_frame : Z -> msolver -> Z -> Assertion)
      (solver_analyze_inert_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (solver_analyze_open_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (stats_rep : Z -> list Z -> Assertion)
      (solver_enqueue_frame : Z -> msolver -> Assertion)
      (solver_record_finish_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_removable_frame_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_reason_levels_frame_at : Z -> msolver -> Z -> Z -> Z -> Assertion)
      (solver_tags_tagged_frame_at : Z -> msolver -> Z -> Z -> Z -> Z -> Assertion)
      (solver_literal_stats_frame_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (real_watch_pair : Z -> list Z -> Prop)
      (solver_db_mutation_frame_at : Z -> msolver -> Z -> Assertion)
      (solver_cancel_frame : Z -> msolver -> Z -> Assertion)
      (solver_levels_slice_at : Z -> msolver -> Z -> Assertion)
      (solver_cancel_undef_tail : msolver -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (solver_cancel_open_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> Z -> Z -> Assertion)
      (clause_remove_pre : Z -> Z -> Z -> Z -> Z -> Z -> list (list Z) -> list Z -> bool -> list Z -> list Z -> list Z -> Assertion)
      (clause_remove_post : Z -> Z -> Z -> Z -> Z -> Z -> list (list Z) -> list Z -> list Z -> list Z -> list Z -> Assertion)
      (clause_remove_open_at : Z -> Z -> Z -> Z -> Z -> list (list Z) -> list Z -> list Z -> list Z -> Assertion)
 */

/* Database, literal, and pointer carriers. */
/*@ Extern Coq
      (db_lookup : dbmap -> Z -> clause_obj -> Prop)
      (clause_db_rep : dbmap -> Assertion)
      (clause_db_pair_remainder : dbmap -> dbmap -> Z -> bool -> list Z -> Assertion)
      (clause_db_pair_focus : dbmap -> dbmap -> Z -> list Z -> Assertion)
      (clause_db_pair_contents : dbmap -> dbmap -> Z -> list Z -> Prop)
      (analyze_tag_step_msolver : msolver -> list Z -> list Z -> Z -> list fp64 -> list Z -> list Z -> fp64 -> msolver)
      (clause_db_pair_frame : dbmap -> dbmap -> Z -> list Z -> Assertion)
      (learnt_db : dbmap -> Prop)
      (lit_wf_c : Z -> Z -> Prop)
      (tag_of_lit : Z -> Z)
      (tag_lit : Z -> Z)
      (is_tag : Z -> bool)
      (lits_denote : list Z -> clause)
      (tagged_word : Z -> Prop)
      (clause_is_lit_result : Z -> Z -> Prop)
      (propagation_ptr_segment : Z -> Z -> Z -> list Z -> Assertion)
      (propagation_int_missing : Z -> Z -> Z -> Z -> list Z -> Assertion)
      (binary_watch_copy_progress : list Z -> list Z -> Z -> list Z -> Z -> Z -> Z -> Z -> list Z -> Prop)
      (propagation_normalized_clause : Z -> Z -> list Z -> list Z)
      (db_pair_lits_update : dbmap -> dbmap -> Z -> list Z -> list Z -> dbmap -> dbmap -> Prop)
      (propagation_migrated_clause : Z -> Z -> Z -> Z -> list Z -> list Z)
      (clause_lits_pointer : Z -> Z -> Prop)
      (clause_hdr_word : bool -> Z -> Z)
      (clause_hdr_addr : Z -> Z)
      (clause_act_addr : Z -> Z)
      (clause_lits_addr : Z -> Z)
      (activity_state : Z -> bool -> Assertion)
      (vecp_remove_found : Z -> list Z -> Z -> Prop)
      (vecp_remove_result : list Z -> Z -> list Z)
      (vecp_remove_member : Z -> list Z -> Prop)
      (vecp_remove_scan_inv : Z -> list Z -> Z -> Prop)
      (vecp_remove_shift_inv : Z -> list Z -> Z -> Z -> list Z -> Prop)
      (clause_simplify_scan_inv : Z -> list Z -> list Z -> Z -> Prop)
      (clause_simplify_result : list Z -> list Z -> Z -> Prop)
      (clause_watch_word : Z -> list Z -> Z -> Z)
      (clause_remove_ready : Z -> Z -> list Z -> list (list Z) -> list Z -> list Z -> Prop)
      (clause_unlocked_words : Z -> list Z -> Prop)
      (learnt_sort_domain : dbmap -> list Z -> Prop)
      (learnt_sort_segment_domain : dbmap -> list Z -> Prop)
      (learnt_sort_context : dbmap -> list fp32 -> Prop)
      (learnt_sort_rep : dbmap -> list fp32 -> Assertion)
      (learnt_cmp_result : dbmap -> list fp32 -> Z -> Z -> Z -> Prop)
      (learnt_sort_alias_remainder : dbmap -> list fp32 -> Z -> list Z -> fp32 -> Assertion)
      (learnt_sort_two_remainder : dbmap -> list fp32 -> Z -> list Z -> fp32 -> Z -> list Z -> fp32 -> Assertion)
      (db_compaction_inv : msolver -> list Z -> Z -> Z -> Prop)
      (db_compaction_step : msolver -> Z -> msolver -> Prop)
      (msolver_reorder_learnts : msolver -> dbmap -> msolver)
      (msolver_heap_project : msolver -> list Z -> list Z -> Z -> msolver)
      (cancel_clear_loop_inv : msolver -> Z -> Z -> list Z -> list Z -> Prop)
      (cancel_reinsert_loop_inv : msolver -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> Prop)
      (capacity_reinsert_loop_inv : msolver -> Z -> Z -> Z -> list Z -> list Z -> Prop)
      (cancel_bound_ready : msolver -> Z -> Prop)
      (selectionsort_outer_inv : dbmap -> list fp32 -> list Z -> list Z -> Z -> Z -> Prop)
      (selectionsort_inner_inv : dbmap -> list fp32 -> list Z -> list Z -> Z -> Z -> Z -> Z -> Prop)
      (sortrnd_partition_inv : dbmap -> list fp32 -> list Z -> list Z -> Z -> Z -> Z -> Z -> Prop)
      (sortrnd_left_scan_inv : dbmap -> list fp32 -> list Z -> list Z -> Z -> Z -> Z -> Z -> Prop)
      (sortrnd_right_scan_inv : dbmap -> list fp32 -> list Z -> list Z -> Z -> Z -> Z -> Z -> Prop)
      (sortrnd_split : dbmap -> list Z -> list Z -> list Z -> list Z -> Z -> Z -> Prop)
 */

/* Heap-order loop carriers. */
/*@ Extern Coq
      (order_heap_wf : Z -> list Z -> list Z -> Prop)
      (order_update_pre : Z -> Z -> list Z -> list Z -> Prop)
      (order_update_loop_inv : Z -> Z -> list Z -> Z -> Z -> list Z -> list Z -> Prop)
      (order_update_post : Z -> Z -> list Z -> list Z -> list Z -> list Z -> Prop)
      (order_unassigned_pre : Z -> Z -> Z -> list Z -> list Z -> Prop)
      (order_unassigned_post : Z -> Z -> Z -> list Z -> list Z -> Z -> list Z -> list Z -> Prop)
      (order_select_pre : Z -> list Z -> list Z -> list Z -> list Z -> Z -> Prop)
      (order_select_loop_inv : Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Prop)
      (order_select_sift_inv : Z -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Prop)
      (order_select_post : Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Prop)
 */

/* Propagation transitions and enqueue state. */
/*@ Extern Coq
      (msolver_propagation_scan_begin : msolver -> Z -> Z -> msolver)
      (propagation_split_pre_words : Z -> Z -> list (list Z) -> list Z -> list (list Z))
      (propagation_split_post_words : Z -> Z -> list (list Z) -> list Z -> list (list Z))
      (propagation_split_pre_caps : Z -> Z -> list Z -> Z -> list Z)
      (propagation_split_post_caps : Z -> Z -> list Z -> Z -> list Z)
      (propagation_scan_keep_step : list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> Prop)
      (propagation_scan_conflict_step : list Z -> list Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Prop)
      (propagation_binary_keep_transition : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> list Z -> list Z -> msolver -> Prop)
      (propagation_real_satisfied_transition : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> dbmap -> dbmap -> list Z -> list Z -> msolver -> Prop)
      (propagation_real_migrated_exit_carrier : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> msolver -> msolver -> msolver -> Z -> dbmap -> dbmap -> list (list Z) -> list (list Z) -> list Z -> list Z -> Z -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> Z -> Z -> Prop)
      (propagation_unit_success_transition : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> Z -> list Z -> dbmap -> dbmap -> list Z -> list Z -> msolver -> Prop)
      (propagation_unit_conflict_transition : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> dbmap -> dbmap -> list Z -> msolver -> Prop)
      (propagation_unit_conflict_ready : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> Z -> Z -> Z -> Z -> list Z -> list Z -> list Z -> dbmap -> dbmap -> msolver -> Prop)
      (propagation_scan_live_finalize : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> msolver -> Z -> Z -> list Z -> msolver -> Prop)
      (propagation_scan_conflict_finalize : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> msolver -> Z -> Z -> Z -> list Z -> msolver -> Prop)
      (enqueue_input : Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> Prop)
      (enqueue_state_at : Z -> Z -> Z -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Assertion)
      (enqueue_post_at : Z -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Assertion)
      (assume_post_at : Z -> Z -> Z -> Z -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Assertion)
      (propagation_scan_open : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> msolver -> msolver -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Z -> Z -> Z -> list Z -> Prop)
      (propagation_scan_candidate_layout : Z -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> Z -> list Z -> Prop)
      (propagation_capacity_target_facts : msolver -> Z -> Z -> Z -> list (list Z) -> list (list Z) -> list Z -> list Z -> Prop)
      (propagation_capacity_abort_state : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> dbmap -> dbmap -> list (list Z) -> list Z -> Z -> Z -> msolver -> Prop)
      (propagation_binary_conflict_exit : Z -> cnf -> list literal -> solver_propagation_context -> msolver -> msolver -> msolver -> msolver -> Z -> Z -> Z -> list Z -> list Z -> list Z -> list Z -> list Z -> list Z -> list Z -> Prop)
      (solver_propagation_scan_core_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Z -> Assertion)
      (propagation_scan_slot : msolver -> Z -> list (list Z) -> list Z -> list (list Z) -> list Z -> Z -> list Z -> Prop)
      (solver_propagation_scan_arrays_noqh_at : Z -> msolver -> Z -> Z -> Z -> Z -> Z -> Z -> Assertion)
 */

/*@ Extern Coq
      (msolver_with_clause_caps_gen : msolver -> Z -> list Z -> Z -> msolver)
      (clause_new_frame_at_gen : Z -> msolver -> Z -> Z -> Assertion)
      (clause_new_transaction_rest_at_gen : Z -> Z -> Z -> Z -> msolver -> Z -> Z -> Assertion)

      (msolver_set_root : msolver -> Z -> msolver)
      (minisat_watch_completed : msolver -> Prop)
      (clause_new_stage_ready_root : Z -> cnf -> list literal -> list literal -> msolver -> msolver -> list Z -> Z -> Z -> Prop)
      (clause_new_capacity_failure_root : Z -> cnf -> list literal -> list literal -> msolver -> msolver -> list Z -> Z -> Z -> Prop)
      (clause_new_success_transition_root : Z -> cnf -> list literal -> list literal -> msolver -> list Z -> Z -> Z -> Z -> msolver -> Prop)
      (clause_new_post_at_root : Z -> Z -> Z -> Z -> Z -> cnf -> list literal -> list literal -> msolver -> list Z -> Z -> Z -> Z -> Z -> Assertion)
      (addclause_support_post_at : Z -> Z -> Z -> cnf -> list literal -> list literal -> msolver -> list Z -> Z -> Assertion)
      (clause_new_reserved_rooms_gen : Z -> list Z -> msolver -> Z -> Prop)
      (clause_install_pending_cert : Z -> cnf -> msolver -> list Z -> bool -> Prop)
       (sorted_le : list Z -> Prop)
      (addclause_sort_outer_inv : Z -> Z -> list Z -> list Z -> list Z -> Prop)
      (addclause_sort_inner_inv : Z -> list Z -> list Z -> list Z -> Prop)
      (addclause_dedup_inv : Z -> list Z -> list Z -> list Z -> Z -> Prop)
      (addclause_prefix_equiv : cnf -> list Z -> list Z -> Prop)
      (addclause_stats_open_frame_wl_at : Z -> msolver -> Z -> Z -> Assertion)
      (solver_assigns_focus_frame_wl_at : Z -> msolver -> Z -> Z -> Assertion)
                     (solver_enqueue_frame_wl : Z -> msolver -> Z -> Assertion)
      (all_from : list Z -> list Z -> Prop)
      (all_ge : Z -> list Z -> Prop)
 */

/* Conditional watcher and resident-conflict preservation across propagation. */
/*@ Extern Coq
      (minisat_propagation_reuse_loop : Z -> msolver -> msolver -> Z -> Prop)
      (minisat_propagation_reuse_scan : msolver -> msolver -> Z -> Z -> list Z -> Prop)
      (minisat_propagation_reuse_live : msolver -> msolver -> Prop)
 */
